@startuml
title 決め打ち処理

走行処理 -> 決め打ち: 実行
activate 決め打ち


opt 青色検知 and タイヤの平均回転角度が11400以上12,000未満
決め打ち -> 右モーター:40を設定
note right: 決め打ち右\nstate=3
決め打ち -> 左モーター:50を設定
end

opt 青色検知 and タイヤの平均回転角度が14700以上15000未満
決め打ち -> 右モーター:50を設定
note right: 決め打ち左\nstate=5
決め打ち -> 左モーター:35を設定
end

opt 青色検知 and タイヤの平均回転角度が19800以上
決め打ち -> 右モーター:40を設定
note right: 決め打ち右\nstate=7
決め打ち -> 左モーター:50を設定
end



決め打ち -> 走行処理

@enduml