@startuml
title ライントレース処理
走行処理 -> ライントレース: 実行
activate ライントレース


== ライントレース右側 ==
alt 明るさが規定値以上
ライントレース -> 右モーター:50を設定
ライントレース -> 左モーター:20を設定

else 明るさが規定値以下
ライントレース -> 右モーター:20を設定
ライントレース -> 左モーター:50を設定
end

== ライントレース左側 ==
alt 明るさが規定値以上
ライントレース -> 右モーター:20を設定
ライントレース -> 左モーター:50を設定

else 明るさが規定値以下
ライントレース -> 右モーター:50を設定
ライントレース -> 左モーター:20を設定
end
deactivate ライントレース

ライントレース -> 走行処理 

@enduml