@startuml
[*] --> state1: プログラムを実行する\nRGBをSに変換する

state1 : ライントレース左()
note right of state1 : ライントレース処理参照
state1 --> state2: S(彩度)の値が0.55以上かつ反射光の値が15以上

state2 : ライントレース左()
state2 --> state3: S(彩度)の値が0.55未満かつ反射光の値が15未満

state3 : ライントレース右()
state3 --> state4: S(彩度)の値が0.55以上かつ反射光の値が15以上

state4 : ライントレース右()
state4 --> state5: S(彩度)の値が0.55未満かつ反射光の値が15未満

state5 : ライントレース左()
state5 --> state6: S(彩度)の値が0.55以上かつ反射光の値が15以上

state6 : ライントレース左()
state6 --> state7: S(彩度)の値が0.55未満かつ反射光の値が15未満

state7 : ライントレース右()
state7 --> state8: S(彩度)の値が0.55以上かつ反射光の値が15以上

state8 : ブレーキモード()
state8 --> [*]: プログラム終了


@enduml